### PR TITLE
Index aliases

### PR DESCRIPTION
**Pull request by Cactusbone**
I've added aliases calls (post and get) 

http://www.elasticsearch.org/guide/reference/api/admin-indices-aliases.html

### CODE REVIEW

**Comment by ramv** [comment]
Thanks for the pull Charly. Will take a look today.

**Comment by Cactusbone** [comment]
Did you have time to take a look?

**Comment by ramv** [comment]
Thanks for the pull! apologize for the delay

**Comment by Cactusbone** [comment]
great! thanks :)

**Pull request merged**
