### PR TITLE
add support for mlt queries (+offline tests)

### PR DESCRIPTION
**Pull request by saalaa**
Hey, I've implemented mlt queries (aka. more_like_this) so now the client supports the shorthand provided by ElasticSearch. For more information:

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-more-like-this.html
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

Feel free to discuss the commit and propose improvements or changes. I'd like to see it integrated in the code base.

Thanks.

### CODE REVIEW

**Comment by ramv** [comment]
Hi Benoit,
I reviewed the code. It is missing online tests. Would you be able to implement those?

**Comment by saalaa** [comment]
Hi Ram. While writing the online tests, I noticed `fields` should have been `mlt_fields` so I corrected the implementation (we have no use for this feature so I hadn't noticed the problem earlier). The online tests and data set ensure that `mlt_fields` now work correctly.

**Comment by saalaa** [comment]
Hey @ramv, thanks for merging the patch. Out of curiosity, do you know when this will be released? I'd like to get rid of our code that works around the lack of `mlt` in the current version of the library so I'm willing to help with the currently open issues if needed.

**Comment by ramv** [comment]
Hi Benoit,
I will try to release it today.

On Mon, Jun 9, 2014 at 6:49 AM, Benoit notifications@github.com wrote:

> Hey @ramv https://github.com/ramv, thanks for merging the patch. Out of
> curiosity, do you know when this will be released? I'd like to get rid of
> our code that works around the limitation of mlt in the current version
> of the library so I'm willing to help with the currently open issues if
> needed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ramv/node-elastical/pull/25#issuecomment-45492015.

## 

Best Regards,

Ram Viswanadha

**Pull request merged**
