### PR TITLE
Add analyze API

### PR DESCRIPTION
**Pull request by baobaab**
Implementation of the Indices Analyze API from Elasticsearch.
http://www.elasticsearch.org/guide/reference/api/admin-indices-analyze/

### CODE REVIEW

**Comment by ramv** [comment]
hmm for some reason this pull request cannot be merged automatically. Need to take a closer look.

**Comment by ramv** [comment]
merged

**Comment by baobaab** [comment]
Hmm, sorry, it seems that something went wrong: I don't see any commit related to this request on master. Please tell me if I could help on something :)

**Comment by ramv** [comment]
interesting. I followed the instructions given by Github. Can you reopen the pull request?

**Comment by baobaab** [comment]
It's ok now, thanks !

**Pull request merged**
