### PR TITLE
Implemented getSettings

### PR DESCRIPTION
**Pull request by jazzzz**

### CODE REVIEW

**Comment by ramv** [comment]
Hi Jazzzz,
thanks for the pull. There are no tests in the pull request. Can you please add them?

**Comment by jazzzz** [comment]
Before adding tests, I would like the current ones to pass. I'm working on Windows XP and ElasticSearch 0.19.11, is there something incompatible with the tests in my configuration?

```
WARNING! The online tests will delete ALL ElasticSearch indices on
localhost to ensure a clean testing environment.

Do you want to continue and delete all indices? (yes/no): yes
node_modules/.bin/vows tests/online-tests.js
????·??·····???·???????????··???·???·?·?·?··? Errored » 15 honored  29 broken  1 errored

Makefile:14: recipe for target `online-tests' failed
make: [online-tests] Error 1 (ignored)
```

**Comment by jazzzz** [comment]
I found the issue: a bad proxy env var curl was using to connect to elastic search.

**Comment by ramv** [comment]
cool. Any update on the tests?

**Comment by jazzzz** [comment]
@ramv did you have some time to check the tests?

**Pull request merged**
