### PR TITLE
dot not transform null into {}

### PR DESCRIPTION
**Pull request by Filirom1**
Curently elastical transform null  value into the empty object.

```
{
  option: null
}
```

become

```
{
  option: {}
}
```

The PR fix this.

ElasticSearch works great with the null value, there is no need to change this behaviour.

### CODE REVIEW

**Comment by feugy** [comment]
Hi there, 

I had the same problem few weeks ago, and fix it locally. It will very handy to integrate it.

Thank you !

**Comment by VirgileD** [comment]
+1

**Comment by ramv** [comment]
I will take a look today.

On Mon, Nov 19, 2012 at 4:27 AM, virgile devaux notifications@github.comwrote:

> +1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ramv/node-elastical/pull/3#issuecomment-10511712.

## 

Best Regards,

Ram Viswanadha

**Comment by Filirom1** [comment]
@ramv is there anything wrong with this Pull Request ?

**Comment by Filirom1** [comment]
Thanks

**Comment by Filirom1** [comment]
@ramv it would be even better to have it on npm ;)

**Comment by ramv** [comment]
will try to get it out by the end of the week.

On Wed, Jan 16, 2013 at 2:32 AM, Romain notifications@github.com wrote:

> @ramv https://github.com/ramv it would be even better to have it on npm
> ;)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ramv/node-elastical/pull/3#issuecomment-12312638.

## 

Best Regards,

Ram Viswanadha

**Comment by ramv** [comment]
Hi Romain,
pushed out a new version of Node Elastical.

On Wed, Jan 16, 2013 at 7:22 AM, Ram Viswanadha rviswanadha@gmail.comwrote:

> will try to get it out by the end of the week.
> 
> On Wed, Jan 16, 2013 at 2:32 AM, Romain notifications@github.com wrote:
> 
> > @ramv https://github.com/ramv it would be even better to have it on
> > npm ;)
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/ramv/node-elastical/pull/3#issuecomment-12312638.
> 
> ## 
> 
> Best Regards,
> 
> Ram Viswanadha

## 

Best Regards,

Ram Viswanadha

**Comment by Filirom1** [comment]
Perfect

**Pull request merged**
